# Generated by Django 4.2.11 on 2025-10-27 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamining_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebMiningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('scores', models.JSONField(default=dict)),
                ('result_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webmining_results', to='datamining_app.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClusteringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('n_clusters', models.IntegerField(default=3)),
                ('silhouette_score', models.FloatField(blank=True, null=True)),
                ('davies_bouldin_score', models.FloatField(blank=True, null=True)),
                ('cluster_labels', models.JSONField(default=list)),
                ('cluster_centers', models.JSONField(blank=True, default=dict, null=True)),
                ('inertia', models.FloatField(blank=True, null=True)),
                ('result_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clustering_results', to='datamining_app.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssociationRuleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_support', models.FloatField(default=0.1)),
                ('min_confidence', models.FloatField(default=0.5)),
                ('frequent_itemsets', models.JSONField(default=list)),
                ('rules', models.JSONField(default=list)),
                ('result_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_results', to='datamining_app.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
